[package]
name = "tazk"
version = "0.2.2"
edition = "2024"
authors = ["NehuÃ©n <github.com/nehu3n>"]
description = "ğŸ• Lightweight, agnostic, fast and easy task runner"
license = "MIT"
repository = "https://github.com/nehu3n/tazk"
readme = "readme.md"
keywords = ["task", "runner", "build", "automation", "cli"]
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils"]
include = [
    "src/*",
    "Cargo.toml",
    "readme.md",
    "license",
]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
glob = "0.3.3"
notify = "8.2.0"
owo-colors = "4.2.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde_yaml = "0.9.34"
toml = "0.9.5"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"