[package]
name = "tazk"
version = "0.1.0"
edition = "2024"
authors = ["NehuÃ©n <github.com/nehu3n>"]
description = "ğŸ• Lightweight, agnostic, fast and easy task runner"
license = "MIT"
repository = "https://github.com/nehu3n/tazk"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
